# Generated by Django 5.2.5 on 2026-02-08 23:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.FloatField(verbose_name='Azote (N)')),
                ('P', models.FloatField(verbose_name='Phosphore (P)')),
                ('K', models.FloatField(verbose_name='Potassium (K)')),
                ('temperature', models.FloatField(verbose_name='Température (°C)')),
                ('humidity', models.FloatField(verbose_name='Humidité (%)')),
                ('ph', models.FloatField(verbose_name='pH du sol')),
                ('rainfall', models.FloatField(verbose_name='Précipitations (mm)')),
                ('label', models.CharField(max_length=50, verbose_name='Culture')),
            ],
            options={
                'verbose_name': 'Donnée de culture',
                'verbose_name_plural': 'Données de cultures',
                'db_table': 'crop_recommendation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('predicted_crop', models.CharField(max_length=50, verbose_name='Culture prédite')),
                ('N', models.FloatField(verbose_name='Azote (N)')),
                ('P', models.FloatField(verbose_name='Phosphore (P)')),
                ('K', models.FloatField(verbose_name='Potassium (K)')),
                ('temperature', models.FloatField(verbose_name='Température (°C)')),
                ('humidity', models.FloatField(verbose_name='Humidité (%)')),
                ('ph', models.FloatField(verbose_name='pH du sol')),
                ('rainfall', models.FloatField(verbose_name='Précipitations (mm)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de prédiction')),
            ],
            options={
                'verbose_name': 'Prédiction',
                'verbose_name_plural': 'Prédictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
